name: 'Publish Arch Linux Package - mobsh-bin'
inputs:
  packageName:
    default: mobsh-bin
  shasum:
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    with:
      ref: aur-publish
  - name: Create PKGBUILD for ${{ inputs.packageName }}
    shell: bash
    run: |
      # Create the output directory
      mkdir -p ./aur/${{ inputs.packageName }}/

      # Strip the leading "v" from the version
      PACKAGE_VERSION="$(echo "${{ github.event.release.tag_name }}" | sed -e 's/^v//')"

      # Output PKGBUILD
      cat > ./aur/${{ inputs.packageName }}/PKGBUILD << EOF
      # Where to file issues: https://github.com/${{ github.repository }}/issues

      pkgname=${{ inputs.packageName }}
      pkgver=$PACKAGE_VERSION
      pkgrel=1
      pkgdesc="Fast git handover with mob"
      arch=('x86_64')
      url="https://github.com/${{ github.repository }}"
      license=('MIT')
      depends=("git")
      optdepends=('espeak-ng-espeak: Multi-lingual software speech synthesizer'
                  'mbrola-voices-us1: An American English female voice for the MBROLA synthesizer')
      provides=('mobsh')
      conflicts=('mobsh' 'mob')

      source_x86_64=("\$url/releases/download/${{ github.event.release.tag_name }}/mob_${{ github.event.release.tag_name }}_linux_amd64.tar.gz")
      sha256sums_x86_64=("${{ inputs.shasum }}")

      package() {
          install -D -m644 "LICENSE" "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
          install -D -m755 "mob" "\$pkgdir/usr/bin/mob"
      }

      EOF
  - name: Publish PKGBUILD for ${{ inputs.packageName }}
    shell: bash
    run: |
      cat ./aur/${{ inputs.packageName }}/PKGBUILD
