on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Show git version
      run: git version
    - uses: actions/checkout@v2
    - name: Use Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: '~1.16.0'
    - name: Test
      run: go test
